### ISSUE TITLE
Industry replacement grfs can fail

### ISSUE THREAD

**Issue by purplemonkeymad** [aidansean/OpenTTD_surveyor#7]
Looks Like Industry set replacements fail:

	INFO:Surveyor:[2021-05-31 14:50:23.292846]  Parsing tile bits...
	Traceback (most recent call last):
	  File ".\src\run.py", line 113, in <module>
		main()
	  File ".\src\run.py", line 107, in main
		surveyor.ingest_data()
	  File ".\OpenTTD_surveyor\src\surveyor.py", line 145, in ingest_data
		self.set_map_bytes()
	  File ".\OpenTTD_surveyor\src\surveyor.py", line 127, in set_map_bytes
		tile.parse_all()
	  File ".\OpenTTD_surveyor\src\tile.py", line 138, in parse_all
		self.occupant.parse_all()
	  File ".\OpenTTD_surveyor\src\tile_occupant.py", line 244, in parse_all
		self.industry_type = INDUSTRY_TYPES[self.parse_map_bits(b'MAP5', 0, 8)]
	IndexError: list index out of range

Specifically a FIRS 4.0.1 grf only. Maybe just use the index number if out of range?

**Comment by aidansean** [comment]
Thanks for the issue report! I wrapped this in a `try...except IndexError` block, and it should now call industries it does not recognise `OTHER_INDUSTRTY`, which should appear as `Other industry` on the images. Please do a `git pull` and try again.

**Comment by purplemonkeymad** [comment]
I can confirm that the error no longer happens on problem saves. (Aside from the wrong industry names, but that is to be expected)
